name: android build

on:
  push:
    branch:
      - master

jobs:
  android_build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'true'
      - name: build debug
        run: |
          ./gradlew app:clean
          ./gradlew app:assembleDebug
      - name: push to server
        run: |
            # push release apk
            export MAINNET_APK=`ls app/build/outputs/apk/MainNetOnekey/debug/*.apk`
            export TESTNET_APK=`ls app/build/outputs/apk/TestNetOnekey/debug/*.apk`
            export REGTEST_APK=`ls app/build/outputs/apk/RegTestOnekey/debug/*.apk`
            export CHANGE_LOG=`git log HEAD -n 1`
            scp "$MAINNET_APK" "$TESTNET_APK" "$REGTEST_APK" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/output/
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /output && ./push.sh $MAINNET_APK '\"$CHANGE_LOG\"' && ./push.sh $TESTNET_APK '\"$CHANGE_LOG\"' && ./push.sh $REGTEST_APK '\"$CHANGE_LOG\"'"
