name: AndroidLint

on:
  pull_request:
    branches:
      - master

jobs:
  android_lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
            submodules: 'true'
      - name: lint check
        run: |
          ~/lint.sh
      - uses: yutailang0119/action-android-lint@v1.0.2
        with:
          xml_path: app/build/reports/lint-results-RegTestOnekeyDebug.xml
      - name: Archive lint artifacts
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: OneKey-android-lint-${{ github.sha }}
          path: |
            app/build/reports/lint-results-RegTestOnekeyDebug.xml
            app/build/reports/lint-results-RegTestOnekeyDebug.html
